name: Deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/NilsOliverLinden/junit-dataprovider.git
      - name: Build
        run: |
          cd junit-dataprovider
          ./gradlew build

