name: Release-JGiven
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'You have to provide a version (e.g. 0.14.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/NilsOliverLinden/JGiven.git
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
      - name: Build & Release
        run: |
          cd JGiven
          git config user.name $ACTOR
          git config user.email "nils-oliver.linden@tngtech.com"

          env
          ./scripts/release.sh ${{ github.event.inputs.version }}
        env:
          ACTOR: ${{ github.actor }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD}}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
