name: Release-JGiven
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'You have to provide a version (e.g. 0.14.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo Cloning
          git clone https://$API_TOKEN_GITHUB@github.com/NilsOliverLinden/JGiven.git
          cd JGiven

          git config --global user.email "action@github.com"
          git config --global user.name $ACTOR

          ./scripts/release.sh ${{ github.event.inputs.version }}
        env:
          ACTOR: ${{ github.actor }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

