name: Release-JGiven
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo Cloning
          git clone https://$API_TOKEN_GITHUB@github.com/NilsOliverLinden/JGiven.git
          cd JGiven

          git config --global user.email "action@github.com"
          git config --global user.name $ACTOR

          echo Commiting
          touch test.txt
          git add test.txt
          git commit -m "Add file from github action"
          git push origin master
        env:
          ACTOR: ${{ github.actor }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './JGiven'
          destination-github-username: 'NilsOliverLinden'
          destination-repository-name: 'JGiven.git'
          user-email: 'action@github.com'

