name: Release-JGiven
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'You have to provide a version (e.g. 0.14.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/NilsOliverLinden/JGiven.git
      - name: Build & Release
        run: |
          cd JGiven
          git config --global user.name $ACTOR
          git config --global user.email "action@github.com"

          ./scripts/release.sh ${{ github.event.inputs.version }}
        env:
          ACTOR: ${{ github.actor }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD}}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
