name: Release-JGiven
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'You have to provide a version (e.g. 0.14.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo Cloning
          git clone https://github.com/NilsOliverLinden/JGiven.git
          cd JGiven

          echo Commiting version ${{ github.event.inputs.version }}
          sed -i -e s/version=.*/version=${{ github.event.inputs.version }} --debug gradle.properties
          git add gradle.properties
          git commit -m "Update version to ${{ github.event.inputs.version }}"

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './JGiven'
          destination-github-username: 'NilsOliverLinden'
          destination-repository-name: 'JGiven.git'
          user-email: 'action@github.com'

