name: Release-JGiven
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          echo Cloning
          git clone https://github.com/NilsOliverLinden/JGiven.git
          cd JGiven

          echo Commiting
          touch test.txt
          git add test.txt
          git commit -m "Add file from github action"

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: './JGiven'
          destination-github-username: 'NilsOliverLinden'
          destination-repository-name: 'JGiven.git'
          user-email: 'action@github.com'

